server:
    port: 0
 
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream, info, health

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest