server:
  port: 8989

#turbine:
#  amqp:
#    port: 8989


---
spring:
  profiles: cloud

management:
  port: -1

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest