server:
  port: 8989

#turbine:
#  amqp:
#    port: 8989

management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream, info, health

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

turbine:
      appConfig: card-statement-composite
      aggregator:
        clusterConfig: CARD-STATEMENT-COMPOSITE
